---
dir: rtl
---

# פעולות על התחיליות

## תחילית אחת

לפעמים צריך להמיר בין סדרי גודל שונים של אותה יחידת בסיס.
למשל:

::: {.card-info}
מהי המסה בקילוגרמים של חתיכת מתכת שמסתה 600 גרם?
:::

בפתרון שלהלן, הרעיון הוא להבין ש**תמיד אפשר להכפיל מספר באחת**!

\begin{align*}
\text{(התחלה) }&\quad&& 600 \text{ g} \\
\text{(כפל באחת) }&&& 1\cdot 600 \text{ g} \\
\text{(בחזקות של עשר) }&&& \underbrace{10^{-3}10^3}_{=1}\cdot 600 \text{ g} \\
\text{(קילו פירושו אלף) }&&& 10^{-3}\underbrace{10^3}_{=\text{k}}\cdot 600 \text{ g} \\
\text{(הצמדת התחילית ליחידה) }&&& 10^{-3}\cdot 600 \text{ kg} \\
\text{(סיום) }&&& 0.6 \text{ kg}
\end{align*}

עכשיו, כשההיגיון שמאחורי ההמרה ברור, אפשר לקצר מעט. התוצאה צריכה להיות ב**קילו**גרמים, ולכן נכתוב $\text{k}$ לצד הגרמים ונכפיל בגורם $10^{-3}$ כדי לאזן את ה״קילו״:

\begin{align*}
\text{(התחלה) }&\quad&& 600 \text{ g} \\
\text{(הוספת התחילית וגורם מאזן) }&&& 10^{-3}\cdot 600 \text{ kg} \\
\text{(סיום) }&&& 0.6 \text{ kg}
\end{align*}

## שתי תחיליות

ננסה דוגמה נוספת, הפעם עם שתי תחיליות.

::: {.card-info}
כמה סנטימטרים יש ב-2 קילומטרים?
:::

בפתרון שלהלן נשתמש בכך ש״סנטי״ פירושו מאית, $\text{c}=10^{-2}$.

\begin{align*}
\text{(התחלה) }&\quad&& 2 \text{ km} \\
\text{(החלפת קילו באלף) }&&& 2\cdot 10^3 \text{ m} \\
\text{(הוספת סנטי וגורם מאזן) }&&& 2\cdot 10^3 \underbrace{10^2 \text{ c}}_{=1} \text{m}\\
\text{(סיום) }&&& 200000 \text{ cm}
\end{align*}

## שתי תחיליות, אבל אחרת

::: {.card-info}
בתמיסה יש 5 מיקרוגרם מלח למיליליטר. מהו הריכוז בגרמים לליטר?
:::

\begin{align*}
\text{(התחלה) }&\quad&& 5 \,\frac{\mu\text{g}}{\text{mL}}\\
\text{(החלפת התחיליות בחזקות של עשר) }&&& 5 \,\frac{10^{-6}\text{g}}{10^{-3}\text{L}}\\
\text{(איחוד החזקות) }&&& 5\cdot 10^{-3} \,\frac{\text{g}}{\text{L}}\\
\text{(סיום) }&&& 0.005 \,\frac{\text{g}}{\text{L}}
\end{align*}

אם לא מקפידים על ספרות משמעותיות, אפשר כנראה לקבל גם את השורה האחרונה כתשובה נכונה, אבל מומלץ לעצור בשורה שלפניה.

## שטחים ונפחים

בהמרת יחידות של שטח או נפח, אל תשכחו להעלות גם את התחיליות בריבוע או בחזקה שלוש.

::: {.card-info}
כמה מטרים רבועים יש בקילומטר רבוע?
:::

$$
1\, \mathrm{km}^2 = 1\, (\mathrm{km})^2 = 1 (\underbrace{10^3}_\text{k} \mathrm{m})^2 = 1 \left( 10^3 \right)^2 \left(\mathrm{m} \right)^2 = 10^6\, \mathrm{m}^2
$$

בקילומטר רבוע יש מיליון מטרים רבועים.

כשכותבים $\mathrm{km}^2$, הכוונה היא שהחזקה חלה גם על ה״קילו״ וגם על ה״מטר״.
בדרך כלל לא כותבים סוגריים במפורש כפי שעשינו למעלה, אבל זו המשמעות.

נראה דוגמה נוספת, הפעם של נפח.

::: {.card-info}
כמה ליטרים יש במטר מעוקב? ליטר אחד הוא הנפח של קובייה שאורך צלעה $10\,\mathrm{cm}$.
:::

$$
1\, \mathrm{m}^3 = (100\, \mathrm{cm})^3 = \left(10 \cdot 10\, \mathrm{cm}\right)^3 = 10^3\left(10\, \mathrm{cm}\right)^3 = 10^3\, \mathrm{L}
$$

במטר מעוקב יש אלף ליטרים.
